version: '3'

services:
  mysql:
    image: mysql:latest
    container_name: mysql
    ports:
      - "3307:3307"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    volumes:
      - ./alchive-db/mysql/data:/var/lib/mysql
      - ./alchive-db/mysql/etc:/etc/mysql/conf.d
    restart: always
    networks:
      - alchive

#  springboot:
#    build:
#      context: .
#      dockerfile: Dockerfile
#    restart: always
#    depends_on:
#      - mysql
#    ports:
#      - 8080:8080
#    container_name: springboot
#    environment:
#      SPRING_DATASOURCE_URL: ${SPRING_DATASOURCE_URL}
#      SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME}
#      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
#      SPRING_PROFILES_ACTIVE: ${SPRING_PROFILES_ACTIVE}
#    networks:
#      - alchive

networks:
  alchive:
    driver: bridge
