apiVersion: 1

datasources:
  - name: Prometheus           # 데이터 소스 이름
    type: prometheus            # 데이터 소스 유형 (Prometheus)
    access: proxy               # Grafana가 Prometheus에 접근하는 방식
    url: http://prometheus:9090 # Prometheus URL (docker-compose로 설정된 이름과 포트 일치해야 함)
    isDefault: true             # 기본 데이터 소스로 설정 (선택 사항)