name: CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 기본 체크아웃
      - name: Checkout
        uses: actions/checkout@v3
      # Gradlew 실행 허용
      - name: Run chmod to make gradlew executable
        run: chmod +x ./gradlew
      # JDK 17 세팅
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      # 환경 변수 설정
      - name: Set environment values
        run: |
          cd ./src/main/resources
          touch ./env.properties
          echo "${{ secrets.ENV_PROPERTIES }}" > ./env.properties
          
          cd /
          touch ./.env
          echo "${{ secrets.ENV }}" > ./.env
        shell: bash
      # Gradle build (Test 제외)
      - name: Build with Gradle
        uses: gradle/gradle-build-action@v2
        with:
          arguments: clean build -x test