name: CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '**'

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 기본 체크아웃
      - name: Checkout
        uses: actions/checkout@v3
      # Gradlew 실행 허용
      - name: Run chmod to make gradlew executable
        run: chmod +x ./gradlew
      # JDK 17 세팅
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      # 환경 변수 설정
      - name: Set environment values
        run: |
          touch ./src/main/resources/env.properties
          echo "${{ secrets.ENV_PROPERTIES }}" > ./src/main/resources/env.properties

        shell: bash
      # Gradle build
      - name: Build with Gradle
        uses: gradle/gradle-build-action@v2
        with:
          arguments: clean build -x test

      # Docker build
      - name: Docker build
        run: |
          echo ${{ secrets.DOCKERHUB_PASSWORD }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
          docker build -t ${{ secrets.DOCKERHUB_REPOSITORY }} .
          docker tag ${{ secrets.DOCKERHUB_REPOSITORY }} ${{ secrets.DOCKERHUB_USERNAME }}/${{ secrets.DOCKERHUB_REPOSITORY }}:${GITHUB_SHA::7}
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/${{ secrets.DOCKERHUB_REPOSITORY }}:${GITHUB_SHA::7}

      # Deploy
      - name: Deploy
        uses: appleboy/ssh-action@master
        with:
          host: 35.216.106.69
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          envs: |
            GITHUB_SHA
            SPING_DATASOURCE_URL=${{ secrets.SPRING_DATASOURCE_URL }}
            SPRING_DATASOURCE_USERNAME=${{ secrets.SPRING_DATASOURCE_USERNAME }}
            SPRING_DATASOURCE_PASSWORD=${{ secrets.SPRING_DATASOURCE_PASSWORD }}
            SPRING_PROFILES_ACTIVE=${{ secrets.SPRING_PROFILES_ACTIVE }}
          script: |
            sudo echo ${{ secrets.DOCKERHUB_PASSWORD }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
            sudo SPRING_DATASOURCE_URL=$SPRING_DATASOURCE_URL \
            SPRING_DATASOURCE_USERNAME=$SPRING_DATASOURCE_USERNAME \
            SPRING_DATASOURCE_PASSWORD=$SPRING_DATASOURCE_PASSWORD \
            SPRING_PROFILES_ACTIVE=$SPRING_PROFILES_ACTIVE \
            docker-compose down
            sudo SPRING_DATASOURCE_URL=$SPRING_DATASOURCE_URL \
            SPRING_DATASOURCE_USERNAME=$SPRING_DATASOURCE_USERNAME \
            SPRING_DATASOURCE_PASSWORD=$SPRING_DATASOURCE_PASSWORD \
            SPRING_PROFILES_ACTIVE=$SPRING_PROFILES_ACTIVE \
            docker-compose up -d